//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuStore.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHANGE_OR_REFUND_PRODUCT
    {
        public int CHANGE_OR_REFUND_PRODUCT_NO { get; set; }
        public string ID { get; set; }
        public string ID_HANDLING_STAFF { get; set; }
        public string ID_WAREHOUSE_STAFF { get; set; }
        public string ID_INVOICE { get; set; }
        public string SERIAL_ID { get; set; }
        public string REASON { get; set; }
        public Nullable<System.DateTime> RETURN_DATE { get; set; }
    
        public virtual STAFF STAFF { get; set; }
        public virtual INVOICE INVOICE { get; set; }
        public virtual STAFF STAFF1 { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
