//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuStore.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMON_USER
    {
        public int USER_NO { get; set; }
        public string ID { get; set; }
        public string ID_USERROLE { get; set; }
        public string ID_STAFF { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string DISPLAYNAME { get; set; }
        public Nullable<bool> HAS_AUTHORITY { get; set; }
    
        public virtual STAFF STAFF { get; set; }
        public virtual USERROLE USERROLE { get; set; }
    }
}
