//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuStore.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER()
        {
            this.INVOICEs = new HashSet<INVOICE>();
        }
    
        public int ID { get; set; }
        public string NAME_ID { get; set; }
        public Nullable<int> ID_INFOR { get; set; }
        public Nullable<int> ID_RANK { get; set; }
        public Nullable<int> PURCHASED_QUANTITY { get; set; }
    
        public virtual RANK RANK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVOICE> INVOICEs { get; set; }
        public virtual INFOR INFOR { get; set; }
    }
}
