//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuStore.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAIL_SPECS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DETAIL_SPECS()
        {
            this.PRODUCT = new HashSet<PRODUCT>();
        }
    
        public int DETAIL_SPECS_NO { get; set; }
        public string ID { get; set; }
        public string ID_COMMON_SPECS { get; set; }
        public string ID_UNIQUE_SPECS { get; set; }
        public string COLOR_CODE { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<decimal> PRICE { get; set; }
    
        public virtual COLOR COLOR { get; set; }
        public virtual COMMON_SPECS COMMON_SPECS { get; set; }
        public virtual UNIQUE_SPECS UNIQUE_SPECS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT> PRODUCT { get; set; }
    }
}
