//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuStore.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAIL_IMPORT_WAREHOUSE
    {
        public int ID_IMPORT_WAREHOUSE { get; set; }
        public int PRODUCT_ID { get; set; }
        public Nullable<double> PRICE_PER_UNIT { get; set; }
    
        public virtual IMPORT_WAREHOUSE IMPORT_WAREHOUSE { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
