//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuStore.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISPLAY_SPECS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DISPLAY_SPECS()
        {
            this.UNIQUE_SPECS = new HashSet<UNIQUE_SPECS>();
        }
    
        public int DISPLAY_SPECS_NO { get; set; }
        public string ID { get; set; }
        public string CODE_DISPLAY { get; set; }
        public string RESOLUTION { get; set; }
        public Nullable<decimal> SIZE { get; set; }
        public Nullable<int> BRIGHTNESS { get; set; }
        public string PANEL { get; set; }
        public string COLOR_SPACE { get; set; }
        public Nullable<int> RefreshRate { get; set; }
        public Nullable<bool> IS_TOUCH_PANEL { get; set; }
        public string SCREEN_TYPE { get; set; }
        public string RATIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNIQUE_SPECS> UNIQUE_SPECS { get; set; }
    }
}
