//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuStore.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPORT_WAREHOUSE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMPORT_WAREHOUSE()
        {
            this.DETAIL_IMPORT_WAREHOUSE = new HashSet<DETAIL_IMPORT_WAREHOUSE>();
        }
    
        public int IMPORT_WAREHOUSE_NO { get; set; }
        public string ID { get; set; }
        public string ID_STORE { get; set; }
        public string ID_STAFF { get; set; }
        public string ID_DISTRIBUTOR { get; set; }
        public decimal TOTAL { get; set; }
        public Nullable<System.DateTime> IMPORT_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETAIL_IMPORT_WAREHOUSE> DETAIL_IMPORT_WAREHOUSE { get; set; }
        public virtual DISTRIBUTOR DISTRIBUTOR { get; set; }
        public virtual STORE STORE { get; set; }
        public virtual STAFF STAFF { get; set; }
    }
}
