//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuStore.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIVE_WARRANTY
    {
        public int ID { get; set; }
        public string NAME_ID { get; set; }
        public int ID_STAFF { get; set; }
        public int ID_INVOICE { get; set; }
        public int PRODUCT_ID { get; set; }
        public string REASON_WARRANTY { get; set; }
        public Nullable<System.DateTime> RECEIVE_DATE { get; set; }
        public Nullable<System.DateTime> RETURN_DATE { get; set; }
        public string STATUS_WARRANTY { get; set; }
    
        public virtual INVOICE INVOICE { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual STAFF STAFF { get; set; }
    }
}
